language: cpp

branches:
  only:
    - master

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release  

before_install:
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update

install:
  - wget --no-check-certificate https://www.cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.1.3-Linux-x86_64.tar.gz
  - sudo cp -fR cmake-3.1.3-Linux-x86_64/* /usr

  - sudo apt-get -qq install gcc-4.9 g++-4.9
  - export CXX="g++-4.9"
  - export CC="gcc-4.9"

before_script:
  - cmake --version
  - $CXX --version
  - $CC --version   

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make
  - make test 

after_failure:
  - cat Testing/Temporary/LastTest.log
