language: cpp

branches:
  only:
    - master

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release  

before_install:
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update

install:
# Install cmake 3.1.3
  - wget --no-check-certificate https://www.cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.1.3-Linux-x86_64.tar.gz
  - sudo cp -fR cmake-3.1.3-Linux-x86_64/* /usr

# Install gcc and g++ (version 4.9)
  - sudo apt-get -qq install gcc-4.9 g++-4.9
  - export CXX="g++-4.9"
  - export CC="gcc-4.9"

# Install cpp-coveralls if build-type is Debug
  - |
      if [ "$BUILD_TYPE" = "Debug" ]; then
        sudo pip install cpp-coveralls
        export CXX_FLAGS=--coverage
        export EXE_LINKER_FLAGS=--coverage
      fi

before_script:
  - cmake --version
  - $CXX --version
  - $CC --version   

script:
  - mkdir build
  - cd build
  - >
      cmake
      -DCMAKE_CXX_COMPILER=$CXX
      -DCMAKE_C_COMPILER=$CC
      -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      -DCMAKE_CXX_FLAGS=$CXX_FLAGS
      -DCMAKE_EXE_LINKER_FLAGS=$EXE_LINKER_FLAGS
      ..
  - make
  - make test 

after_failure:
  - cat Testing/Temporary/LastTest.log

after_success:
  - coveralls --root .. --gcov-options '\-lp' --include include
