language: cpp

branches:
  only:
    - master

compiler: gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release  

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get -qq update
  - sudo apt-get -qq upgrade

install:
  - sudo apt-get -qq upgrade

before_script:
  - cmake --version
  - $CXX --version
  - $CC --version   

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make
  - make test 
